spring:
  application:
    name: technical-test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:~/user
    url: jdbc:h2:file:/data/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    generate-ddl: true
#    defer-datasource-initialization: true
  sql:
    init:
      mode: always
